services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: llm_jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
      - .:/var/jenkins_home/workspace/llm-engineering
      - //c/Users/gorke/AppData/Roaming/Python/Scripts/poetry:/usr/local/bin/poetry:ro
      - //c/Program Files/Python311/python.exe:/usr/bin/python3:ro

volumes:
  jenkins_data: